version: '3.7'

services:
  app:
    restart: always
    ports:
    - "8000:8000"
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      -  '.:/src'
    env_file:
      - .env.local
    command: ["./docker-entrypoint.sh"]
  postgres:
    image: postgres:13.2
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pokemon_viewer_db_data:/var/lib/postgresql/data
    env_file:
      - .env.local
  redis:
    image: redis
    restart: always
    expose:
      - 6379
    volumes:
      - pokemon_viewer_redis_data:/data
  celery:
    restart: always
    build:
      context: .
    command: ["celery", "-A", "pokemon_viewer_backend", "worker", "-l", "info", "--beat"]
    env_file:
      - .env.local
    depends_on:
      - postgres
      - redis
      - app
  flower:
    image: mher/flower:0.9.7
    command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
    ports:
      - "5555:5555"
    depends_on:
      - redis
volumes:
    pokemon_viewer_db_data:
    pokemon_viewer_redis_data:
