EXTENSIONS = ["csv"]

IMPORT_NAME_COLUMN = "Name"
IMPORT_TYPE_1_COLUMN = "Type 1"
IMPORT_TYPE_2_COLUMN = "Type 2"
IMPORT_TOTAL_COLUMN = "Total"
IMPORT_HP_COLUMN = "HP"
IMPORT_ATTACK_COLUMN = "Attack"
IMPORT_DEFENCE_COLUMN = "Defense"
IMPORT_SP_ATTACK_COLUMN = "Sp. Atk"
IMPORT_SP_DEFENCE_COLUMN = "Sp. Def"
IMPORT_SPEED_COLUMN = "Speed"
IMPORT_GENERATION_COLUMN = "Generation"
IMPORT_LEGENDARY_COLUMN = "Legendary"

FILE_COLUMNS = [
    IMPORT_NAME_COLUMN,
    IMPORT_TYPE_1_COLUMN,
    IMPORT_TYPE_2_COLUMN,
    IMPORT_TOTAL_COLUMN,
    IMPORT_HP_COLUMN,
    IMPORT_ATTACK_COLUMN,
    IMPORT_DEFENCE_COLUMN,
    IMPORT_SP_ATTACK_COLUMN,
    IMPORT_SP_DEFENCE_COLUMN,
    IMPORT_SPEED_COLUMN,
    IMPORT_GENERATION_COLUMN,
    IMPORT_LEGENDARY_COLUMN
]

COLUMNS_NAMES_MAP = {
    IMPORT_NAME_COLUMN: "name",
    IMPORT_TYPE_1_COLUMN: "type_1",
    IMPORT_TYPE_2_COLUMN: "type_2",
    IMPORT_TOTAL_COLUMN: "total",
    IMPORT_HP_COLUMN: "hp",
    IMPORT_ATTACK_COLUMN: "attack",
    IMPORT_DEFENCE_COLUMN: "defence",
    IMPORT_SP_ATTACK_COLUMN: "sp_attack",
    IMPORT_SP_DEFENCE_COLUMN: "sp_defence",
    IMPORT_SPEED_COLUMN: "speed",
    IMPORT_GENERATION_COLUMN: "generation",
    IMPORT_LEGENDARY_COLUMN: "legendary"
}